Nov = (input("Enter a value for find and index:"))
print(Nov.find("Monday"))
print(Nov.index("y"))
x= (input("Enter a value That u want to split:"))
print(x.split())
x = (input("Enter a string to convert it into uppercase:"))
print(x.upper())
x = (input("Enter a string to convert it into Lowercase:"))
print(x.lower())
x = (input("Enter a string to convert it into titlt:"))
print(x.title())
x = (input("Enter a string to convert it into swap:"))
print(x.swapcase())
x = (input("Enter a string to convert it into capitilize:"))
print(x.capitalize())
x = (input("Enter a sting to check if it is a isupper:"))
print(x.isupper())
x = (input("Enter a sting to check if it is a islower:"))
print(x.islower())
x = (input("Enter a sting to check if it is a isalnum:"))
print(x.isalnum())
x = (input("Enter a sting to check if it is a isdigit:"))
print(x.isdigit())
x = (input("Enter a sting to check if it is a istitle:"))
print(x.istitle())
text = (input("Enter a string to check starting string"))
print(text.startswith("skywaves"))
